import assert from 'node:assert/strict'
import { readFile, stat } from 'node:fs/promises'
import { join } from 'node:path'
import { test } from 'node:test'

import { buildClientApp } from '../src/build/buildClientApp.mjs'
import { renderMarkdownToHtml } from '../src/vendor/marknote/index.mjs'
import { createFixtureSite } from './helpers.mjs'

test('buildClientApp emits a client-rendered app shell, content manifest, and write page', async () => {
  const fixture = await createFixtureSite()
  try {
    await buildClientApp({ rootDir: fixture.root })
    const home = await readFile(join(fixture.root, 'index.html'), 'utf8')
    const manifest = await readFile(join(fixture.root, 'content/manifest.json'), 'utf8')
    const appScript = await readFile(join(fixture.root, 'assets/scripts/app.js'), 'utf8')
    const contentData = await readFile(join(fixture.root, 'assets/scripts/content-data.js'), 'utf8')
    const styles = await readFile(join(fixture.root, 'assets/styles/global.css'), 'utf8')
    const katexStyles = await readFile(join(fixture.root, 'assets/styles/katex.min.css'), 'utf8')
    const login = await readFile(join(fixture.root, 'login/index.html'), 'utf8')
    const write = await readFile(join(fixture.root, 'write/index.html'), 'utf8')
    await stat(join(fixture.root, 'assets/styles/colors.css'))
    await stat(join(fixture.root, 'assets/styles/fonts/KaTeX_Main-Regular.woff2'))
    assert.match(home, /href="assets\/styles\/global\.css"/)
    assert.match(home, /href="assets\/styles\/katex\.min\.css"/)
    assert.match(home, /href="login\/index\.html"/)
    assert.match(home, /href="write\/index\.html"/)
    assert.match(home, /data-admin-login-nav/)
    assert.match(home, /data-write-nav hidden/)
    assert.match(home, /devnote-authoring-token:MonoBhvr\/DevNote/)
    assert.match(home, /localStorage\.getItem\(k\)/)
    assert.match(home, /관리자 로그인/)
    assert.match(home, /글쓰기/)
    assert.match(home, /data-theme="system"/)
    assert.match(home, /data-theme-select/)
    assert.match(home, /assets\/scripts\/app\.js/)
    assert.doesNotMatch(home, /type="module"/)
    assert.match(manifest, /content\/projects\/marknote\/series\/syntax\/posts\/block-system\/content\.mnote/)
    assert.match(appScript, /DEVNOTE_CONTENT/)
    assert.match(appScript, /giscus\.app\/client\.js/)
    assert.match(appScript, /data-category-id/)
    assert.match(appScript, /createElement\("script"\)/)
    assert.match(appScript, /data-giscus-root/)
    assert.match(contentData, /content\/projects\/marknote\/series\/syntax\/posts\/block-system\/content\.mnote/)
    assert.match(contentData, /R_test/)
    assert.match(katexStyles, /@font-face/)
    assert.match(katexStyles, /fonts\/KaTeX_Main-Regular\.woff2/)
    assert.match(renderMarkdownToHtml('본문 $x^2$.'), /class="katex"/)
    assert.match(login, /관리자 로그인/)
    assert.match(login, /data-admin-login-nav/)
    assert.match(login, /data-write-nav hidden/)
    assert.match(login, /GitHub 로그인/)
    assert.match(login, /data-login-panel/)
    assert.match(login, /data-token/)
    assert.match(login, /href="\.\.\/write\/index\.html"/)
    assert.match(write, /글쓰기/)
    assert.match(write, /data-admin-login-nav/)
    assert.match(write, /data-write-nav hidden/)
    assert.match(write, /data-write-guard hidden/)
    assert.doesNotMatch(write, /관리자 로그인이 필요합니다/)
    assert.doesNotMatch(write, /글쓰기는 관리자 로그인 후 사용할 수 있습니다/)
    assert.doesNotMatch(write, /data-login-panel/)
    assert.doesNotMatch(write, /data-token/)
    assert.match(write, /data-logout/)
    assert.match(write, /data-session-status/)
    assert.doesNotMatch(write, /&quot;repo&quot;/)
    assert.match(write, /"repo":"MonoBhvr\/DevNote"/)
    assert.match(write, /data-writing-workspace hidden/)
    assert.match(write, /data-editor-pane/)
    assert.match(write, /data-preview-pane/)
    assert.match(write, /marknote-content/)
    assert.match(styles, /\[hidden\] \{\n  display: none !important;/)
    assert.match(styles, /background: var\(--marknote-block-color, var\(--color-marknote-block-bg\)\)/)
    assert.match(styles, /--marknote-block-color: #fff1f2/)
    assert.match(styles, /--marknote-block-color: #eff6ff/)
    assert.match(styles, /--marknote-block-color: #ecfdf5/)
    assert.match(styles, /--marknote-block-color: #fefce8/)
    assert.match(styles, /--marknote-block-color: #fff7ed/)
    assert.match(styles, /--marknote-block-color: #faf5ff/)
    assert.match(styles, /--marknote-block-color: #f5f5f4/)
    assert.match(styles, /marknote-block-has-type:not\(\.marknote-fold\)/)
    assert.doesNotMatch(styles, /marknote-block-type-warning[\s\S]*background:/)
    assert.doesNotMatch(styles, /marknote-block-type-question[\s\S]*background:/)
    assert.doesNotMatch(home, /\/DevNote\//)
  } finally {
    await fixture.cleanup()
  }
})
